const colors = {
  primary: '#1565C0',
  primaryDark: '#0D47A1',
  accent: '#00B0FF',
  success: '#00C853',
  danger: '#F44336',
  warning: '#FF9800',
  background: '#0A0E1A',
  surface: '#141929',
  surfaceElevated: '#1C2438',
  foreground: '#F5F5F5',
  muted: '#8A9BB5',
  border: '#253050',
  
  // Light mode specific colors
  backgroundLight: '#F5F7FA',
  surfaceLight: '#FFFFFF',
  foregroundLight: '#0A0E1A',
};

export default {
  light: {
    background: colors.backgroundLight,
    foreground: colors.foregroundLight,
    card: colors.surfaceLight,
    cardForeground: colors.foregroundLight,
    primary: colors.primary,
    primaryForeground: '#FFFFFF',
    secondary: colors.surfaceElevated,
    secondaryForeground: colors.foreground,
    muted: colors.border,
    mutedForeground: colors.muted,
    accent: colors.accent,
    accentForeground: '#FFFFFF',
    destructive: colors.danger,
    destructiveForeground: '#FFFFFF',
    border: colors.border,
    input: colors.border,
    success: colors.success,
    warning: colors.warning,
    primaryDark: colors.primaryDark,
  },
  dark: {
    background: colors.background,
    foreground: colors.foreground,
    card: colors.surface,
    cardForeground: colors.foreground,
    primary: colors.primary,
    primaryForeground: '#FFFFFF',
    secondary: colors.surfaceElevated,
    secondaryForeground: colors.foreground,
    muted: colors.border,
    mutedForeground: colors.muted,
    accent: colors.accent,
    accentForeground: '#FFFFFF',
    destructive: colors.danger,
    destructiveForeground: '#FFFFFF',
    border: colors.border,
    input: colors.border,
    success: colors.success,
    warning: colors.warning,
    primaryDark: colors.primaryDark,
  },
  radius: 8,
};